copy into {{ database }}.{{ schema }}.VENDOR1_BASIC_METRICS (
    "DATE",
    "CHANNEL_ID",
    "CHANNEL_NAME",
    "ITEM_ID",
    "LIVE_OR_ON_DEMAND",
    "SUBSCRIBED_STATUS",
    "COUNTRY_CODE",
    "VIEWS",
    "COMMENTS",
    "LIKES",
    "DISLIKES",
    "SHARES",
    "WATCH_TIME_MINUTES",
    "AVERAGE_VIEW_DURATION_SECONDS",
    "AVERAGE_VIEW_DURATION_PERCENTAGE",
    "ANNOTATION_IMPRESSIONS",
    "ANNOTATION_CLICKABLE_IMPRESSIONS",
    "ANNOTATION_CLICKS",
    "ANNOTATION_CLICK_THROUGH_RATE",
    "ANNOTATION_CLOSABLE_IMPRESSIONS",
    "ANNOTATION_CLOSES",
    "ANNOTATION_CLOSE_RATE",
    "CARD_TEASER_IMPRESSIONS",
    "CARD_TEASER_CLICKS",
    "CARD_TEASER_CLICK_RATE",
    "CARD_IMPRESSIONS",
    "CARD_CLICKS",
    "CARD_CLICK_RATE",
    "SUBSCRIBERS_GAINED",
    "SUBSCRIBERS_LOST",
    "ITEMS_ADDED_TO_PLAYLISTS",
    "ITEMS_REMOVED_FROM_PLAYLISTS",
    "RED_VIEWS",
    "RED_WATCH_TIME_MINUTES",
    "CLIENTNAME_SOURCE_KEY",
    "CLIENTNAME_LOADED_TS",
    "CLIENTNAME_START_DATE",
    "CLIENTNAME_END_DATE",
    "CLIENTNAME_FLOW_RUN_ID"
) from ( 
    select
        $1:date::text DATE,
        $1:channel_id::text CHANNEL_ID,
        '{{ channel_name }}' CHANNEL_NAME,
        $1:item_id::text VENDOR1_ITEM_ID,
        $1:live_or_on_demand::text LIVE_OR_ON_DEMAND,
        $1:subscribed_status::text SUBSCRIBED_STATUS,
        $1:country_code::text COUNTRY_CODE,
        $1:views::number VIEWS,
        $1:comments::number COMMENTS,
        $1:likes::number LIKES,
        $1:dislikes::number DISLIKES,
        $1:shares::number SHARES,
        $1:watch_time_minutes::number WATCH_TIME_MINUTES,
        $1:average_view_duration_seconds::double AVERAGE_VIEW_DURATION_SECONDS,
        $1:average_view_duration_percentage::double AVERAGE_VIEW_DURATION_PERCENTAGE,
        $1:annotation_impressions::number ANNOTATION_IMPRESSIONS,
        $1:annotation_clickable_impressions::number ANNOTATION_CLICKABLE_IMPRESSIONS,
        $1:annotation_clicks::number ANNOTATION_CLICKS,
        $1:annotation_click_through_rate::number ANNOTATION_CLICK_THROUGH_RATE,
        $1:annotation_closable_impressions::number ANNOTATION_CLOSABLE_IMPRESSIONS,
        $1:annotation_closes::number ANNOTATION_CLOSES,
        $1:annotation_close_rate::number ANNOTATION_CLOSE_RATE,
        $1:card_teaser_impressions::number CARD_TEASER_IMPRESSIONS,
        $1:card_teaser_clicks::number CARD_TEASER_CLICKS,
        $1:card_teaser_click_rate::number CARD_TEASER_CLICK_RATE,
        $1:card_impressions::number CARD_IMPRESSIONS,
        $1:card_clicks::number CARD_CLICKS,
        $1:card_click_rate::number CARD_CLICK_RATE,
        $1:subscribers_gained::number SUBSCRIBERS_GAINED,
        $1:subscribers_lost::number SUBSCRIBERS_LOST,
        $1:items_added_to_playlists::number ITEMS_ADDED_TO_PLAYLISTS,
        $1:items_removed_from_playlists::number ITEMS_REMOVED_FROM_PLAYLISTS,
        $1:red_views::number RED_VIEWS,
        $1:red_watch_time_minutes::number RED_WATCH_TIME_MINUTES,
        metadata$filename CLIENTNAME_SOURCE_KEY,
        current_timestamp() as CLIENTNAME_LOADED_TS,
        TO_DATE($1:date::text, 'YYYYMMDD') CLIENTNAME_START_DATE,
        DATEADD(day, 1, TO_DATE($1:date::text, 'YYYYMMDD')) CLIENTNAME_END_DATE,
        '{{ flow_run_id }}'
    from
        @{{ database }}.{{ schema }}.{{ mount_location }}/{{ file_name }})
    file_format = (
        TYPE = 'PARQUET' 
        COMPRESSION = 'AUTO')
    FORCE = TRUE


